### ISSUE TITLE
Suggestion: make invites distributed in a better way

### ISSUE THREAD

**Issue by KruciferX** [idena-network/idena-desktop#311]
Currently some humans, even the old age ones, get no invites cause of bad flip posters that impact their score.

What was meant to be an advantage for humans became a source of frustration for many of them.

So instead of having a minimum score to be eligible for an invite, I propose a different solution.

Each human should always get at least 1 invite, no matter which score he/she has.

Second invite should be spread among higher score humans (and maybe also verified), the way it is now.

So a human with 92% would always get an invite, but a human with 95% would get 2.

That way we have incentive to keep human status even with barely human percentage.

**Comment by RealMahmoud** [comment]
Hello .. what about Changing the score calculation ? to make it instead of all validation to latest 5 or 6 ? 
If we looked at my Identity here https://scan.idena.io/identity/0xb30348813590e02907da79e1c46fba4edca5a2d8 
you will find that i am human with age 8 and i didn't got any invites ..and i am not running any extra identities ..so it's kinda unfair 🙂 
i also posted it here and got some ^yes^ votes https://idena.vote/proposal.php?id=5

**Comment by busimus** [comment]
This is [being implemented](https://github.com/idena-network/idena-go/pull/485) in the node, but the changes still maintain the global invite limit (i.e. humans have priority to get 1 invite, but some humans might get nothing if there are more humans than total invites).

**Comment by KruciferX** [comment]
Yes, I'm aware of that. But it will be much more fair than now.

And I believe that in current state of network, every human will get an invite.
