### ISSUE TITLE
Failed Validation

### ISSUE THREAD

**Issue by xaochuk** [idena-network/idena-desktop#470]
15.11.2020 validation was failed, because i think you your technical problem. I will send also screenshot.

1. At fast validation 2 of 6 flips was written "no data avalialible. please skip the flip".
2. I push button submit before 14 second till validation end (make screenshot later).
![validation](https://user-images.githubusercontent.com/48527184/99191161-ec121200-277b-11eb-9a43-2470d4e2fe72.jpg)
3. But validation was failed because of (Late-Submission)
My explorer - https://scan.idena.io/identity/0xad2dda829db4bd4b87c3aee104ee58214407b2c7/epoch/58/validation

Sorry, but i think it's not honestly. If i have 2 min for fast validation, it's means that i have 2 minutes to choose flips and push button "submit answer". But looking how working your client version now, looks like i have 1:30 to solve flips and 30 second to wait, whille is going "sumbit answer"

Answer me please.

**Comment by xaochuk** [comment]
my log from client 
[idena.log](https://github.com/idena-network/idena-desktop/files/5542786/idena.log)

**Comment by rioda-org** [comment]
It would be great if you can also include node logs

**Comment by rioda-org** [comment]
It is recommended to go to through pre-validation check of your technical setup of Idena App and node. It will be a lot of information, try to do things that seem easy enough for you to do. Please consider these few advices:


**1. Time synchronisation**
Time synchronisation is of great importance for successful validation. Experience tells me that Windows users are affected mostly with time synchronisation issue. Thing is, windows has built-in time synchronisation which synchronises time once in 7 days. So it is very likely that you will be out of sync to some extent on validation day. To check how much in sync your PC is right now, visit time.is website.
Problem:
What can out-of-sync cause during validation? It can fool Idena app to show you wrong time during short session. You can have 16 seconds displayed as remaining time, but in fact if your PC time is out of sync for let's say 19 seconds, you have already missed the time to submit your answers, so you can fail validation short session with result "Late Submission".
Solution:
Install free program that can sync your time more often. You can download it by visiting website NetTime, or download it directly from this link. Allow it to be installed as a service so it runs automatically in the background.


**2. Internet connection**
Idena at home:
If you run node in a home environment, there is whole lot of things to consider that can cause problems:
- Router quality: Did your internet start disconnecting from time to time while using idena? Many home routers are made in low quality and can't handle this kind of traffic and connections that Idena is making. Regular cisco will work like a charm. If you replace your current router that is disconnecting with some regular cisco or mikrotik, you will not have problems. You can restart your router one day before validation so it clears its cache if it has any, so it can serve you as good as it can on validation day. You can also configure your node to use config.json to block private ip ranges scanning, that should help your router to get less traffic and less load. See how to do that on this video (read video description).
- Wi-Fi: Are you running Idena on laptop over Wi-Fi? How good is your Wi-Fi? Since wifi is something unpredictable, if you know from experience that your wifi is sometimes unstable, it is recommended to hook up a lan cable during validation session so you avoid potential problems.
- Other people in house and programs: Are you running other programs like torrent or are you on a shared internet? Turn off all other things that are using internet during validation time, and ask your roommates/family members not to use internet during validation time (It's just 15min once in a 2 weeks).
- Internet speed: I don't have exact data but 1mbps of upload speed would be questionable recommended minimum for validation of one Idena on that internet using --profile=lowpower option. See how to setup that option on this video (read video description).


**3. Hardware resources and performance**
Hardware requirements is complicated subject as there are many possible setups and pc hardware on which you can run full Idena App or just node. As I don't have much experience with all devices (like RaspberryPi or Mac's) and operating systems like all possible Linux distributions, I will try to give general suggestions.
**CPU power:** validation is more cpu intensive than in-between validation node mining. So if your mining is working ok, that does not mean that your validation will go ok if you limit your CPU for Idena in some way. If you use Idena on laptop on windows and connect to it remotely, don't close lid of your laptop as it will disable graphics card and your CPU will maybe have problem to deal with all that needs to be done and possibly go out of sync during validation. Also some PC's/Operating systems disable graphics card if you don't have monitor attached, that can also cause issues in getting all computational load on CPU.
**RAM memory:** I have noticed that node starts by using 120MB of RAM. Over time, if you don't restart it, it consumes more and more memory. I have seen it go up to 800MB after 7-10 days of non stop activity. This is very problematic for VPS that have 1GB of RAM. If you have swap file(virtual memory on hard disk), it will help but not for long. After some time I guess CPU has to deal with node and ram and swap and node starts to go offline from time to time. It is very recommended to restart your node one day before validation. Not right before validation as then load on network is high and if you are not lucky, you might not connect to peers fast enough. After you restart node, it will go to using 200MB of ram and it will be in best condition for validation.
Please don't use VPS's with Windows and 2GB of ram, you will maybe pass one validation, but will fail next for sure. For VPS with Windows, 4GB is minimum for normal funcioning for you to be safe and not fail validation.

**Comment by aidenaio** [comment]
closing this
