### ISSUE TITLE
Flip marked as "No answer" although not presented in Validation at all

### ISSUE THREAD

**Issue by vojch** [idena-network/idena-desktop#549]
In the results of the last validation ceremony (epoch: 65) I see there is a flip that was marked as "No answer", although I solved all the flips that were presented.
I was not presented with the flip in question.

Could we correct this somehow, since my score dropped because of this?

This is the link for the flip I mentioned.

https://scan.idena.io/flip/bafkreihkpxo7w4heau2yeygb4hf3ehp4u4i7xztfbgdljqbjniwfjkd7ya

**Idena Client logs**
I attached my Idena client logs here:
[idena-client.log](https://github.com/idena-network/idena-desktop/files/6131287/idena-client.log)

**Idena Node logs**
I attached my Idena node logs here:
[idena-node.log](https://github.com/idena-network/idena-desktop/files/6131580/idena-node.log)

**Validation context**
- Identity status before ➡️ Identity status after
Newbie ➡️ Verified

- Identity address:
0x85710e1ad405d1046ee074555892b5d347628df8

- Link to the Explorer page with the current validation: 
https://scan.idena.io/identity/0x85710e1ad405d1046ee074555892b5d347628df8/epoch/65/validation#shortAnswers

**Environment:**
 - OS: Windows 10 Pro, build: 18363.1440
 - Node mode: Ubuntu VPS on DigitalOcean
 - Client version: 0.21.2
 - Node version 0.24.3

**Comment by rPman** [comment]
The same bug for me and my second family account, also people talk about it in chats
#70 epoch, client 0.24.2 windows, node 0.26.3 linux and windows

nodes started as separated processes, one node on linux server (configured to be shared node for experiments, also work as delegated miner for all my family accounts), second node on windows machine, both in local network

**Comment by ubiubi18** [comment]
I had two flips marked as 'no answer' as well in long session, i know they did show up and i definately voted on them, but twice, changed my mind and revoted from left to right. That was a close call to get killed ;/

**Comment by DyuldinKS** [comment]
Good evening!
It seems that I encountered the same problem on the validation today, epoch #0072. The flip I voted for is not presented in my validation results - https://scan.idena.io/flip/bafkreif7kvrtrjigy3ctjwnhws64s4pe7u42ubwa7ntaxc52xkwipfc7nq (found it in the client logs).

I probably had not the best internet connection, had to use a smartphone as a wifi router, so I only received 4 flips during the short session, and I am completely sure that I voted them all. But the validation results contain only 3 of 4 flips that I voted. And other 3 flips, which marked unanswered, are not familiar to me.

So, presumably I lost my stake because of the bug, and really hope my logs will help determine and fix it.

**Validation context**
status: Verified -> Not validated
identity: 0x1df1e66d44c4414a9d927ebbe6ab7663a1bc0686
https://scan.idena.io/identity/0x1df1e66d44c4414a9d927ebbe6ab7663a1bc0686/epoch/72/validation#shortAnswers

**Environment:**

OS: macOS 11.3.1 (20E241)
Node mode: remote, Digital Ocean 
Client version: 0.22.3
Node version: 0.26.6

**Idena Client logs**
[client.log](https://github.com/idena-network/idena-desktop/files/6873060/client.log)

**Idena Node logs**
[local-node.log](https://github.com/idena-network/idena-desktop/files/6873061/local-node.log)
[remote-node.log](https://github.com/idena-network/idena-desktop/files/6873062/remote-node.log)

**Comment by DyuldinKS** [comment]
Does anyone investigate it?
cc @aidenaio @midenaio

**Comment by midenaio** [comment]
The issue may arise due to a weak internet connection. As a result node did not get a flip key required for the flip decryption while the other participants did (more than 50% of the network). 

If a node does not receive a flip key during the first 30 seconds of validation, an extra flip is used instead. There are 2 extra flips that can be used if some of the 6 basic flips aren't available (authors are offline) and no one can solve them. However if a basic flip is available for 50%+ of the network then it must be solved by the user during the short session, thus the extra flip answer does not count (the answer is not displayed in the blockchain explorer as well).

Validation shading should reduce network load and improve flip keys delivery.
