### ISSUE TITLE
Trojan virus in client version 0.27.3

### ISSUE THREAD

**Issue by an-trader** [idena-network/idena-desktop#714]
**In the new version of the client (0.27.3) was detected a trojan - many participants do not want to update the client!**
What exactly have you added to the new version of the client?
Please provide clarification and solve the problem
![Trojan](https://user-images.githubusercontent.com/87753268/136367752-0b4703ff-975a-4547-a0e4-25c8b45d8756.jpg)
![Trojan2](https://user-images.githubusercontent.com/87753268/136367756-fd21c598-962e-4ef0-9231-557666d4684d.jpg)

**Comment by aidenaio** [comment]
that's a false positive from your antivirus software caused by `canvas` dependency which is actually an npm module used as a dependency for the image editor you used for creating flips.

here is the full diff between two consecutive versions https://github.com/idena-network/idena-desktop/compare/v0.27.1...v0.27.3

every single line of code or pull request is available under this repo. no need to worry
